# apiVersion: backstage.io/v1alpha1
# kind: Component
# metadata:
#   name: product-app
#   annotations:
#     # github.com/project-slung: Sada-r/productDetails-app 
#     # backstage.io/techdocs-ref: dir:.
#     # github.com/project-slung: Sada-r/productDetails-app
#     backstage.io/source-template: template:default/productDetails-app
#     backstage.io/linguist: https://github.com/Sada-r/productDetails-app/tree/master
# spec:
#   type: service
#   owner: user:guest
#   lifecycle: experimental
#   providesApis:
#     - product-api

# ---

# apiVersion: backstage.io/v1alpha1
# kind: API
# metadata:
#   name: product-api
#   description: This product api gives some dummy products
# spec:
#   type: openapi
#   lifecycle: experimental
#   owner: user:guest
#   definition:
#     $text: https://github.com/Sada-r/productDetails-app/blob/master/dummy-product-api-swagger.json


apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: product-app
  annotations:
    # github.com/project-slung: Sada-r/productDetails-app 
    # backstage.io/techdocs-ref: dir:.
    backstage.io/source-template: template:default/productDetails-app
    backstage.io/linguist: https://github.com/Sada-r/productDetails-app/tree/master
    
spec:
  type: service
  owner: guests
  lifecycle: experimental
  providesApis:
    - product-api

---

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: product-api
  description: This product api gives some dummy products
spec:
  type: openapi
  lifecycle: experimental
  owner: guests
  definition:
    $text: https://github.com/Sada-r/productDetails-app/blob/master/dummy-product-api-swagger.json