apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Token-Balance-App
  description: This is a Node.js app to get current token balance
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags:
    - node 

spec:
  type: service
  owner: guests
  lifecycle: experimental
  ststem: test-app
  providesApis:
    - Tier1-token-api
    - Tier2-token-api

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: Tier1-token-api
  description: Token Balance details for Tier1_Supplier
spec:
  type: openapi
  owner: guests
  lifecycle: experimental
  ststem: test-app
  definition:
    $text: https://github.com/Sada-r/tokenBalance/blob/master/tier1-supplier-api-swagger.json

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: Tier2-token-api
  description: Token Balance details for Tier2_Supplier
spec:
  type: openapi
  owner: guests
  lifecycle: experimental
  ststem: test-app
  definition:
    $text: https://github.com/Sada-r/tokenBalance/blob/master/tier2-supplier-api-swagger.json 