apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: dummy-product-api
  description: This product api gives some dummy products
spec:
  type: openapi
  lifecycle: experimental
  owner: user:guest
  definition:
    $text: https://github.com/Sada-r/productDetails-app/blob/master/dummy-product-api-swagger.json